### ISSUE TITLE
🚀 Home Page

### ISSUE THREAD

**Issue by Mackignacio** [mayajs/mayajs.io#2]
## 📝 Description
As our framework grows the learning curve for new users become steeper. We need a platform for them to read the docs and learn the basics. Also this platform will cater all the new upcoming features and news about the framework. This page will be the first page for MayaJS website.

## 📋 Todo:

- [ ] Logo and basic details section
- [ ] Features section
- [ ] Company section
- [ ] Why MayaJS section
- [ ] Contact section
- [ ] News section
- [ ] FAQ section

**Comment by johnhigginsavila** [comment]
![image](https://user-images.githubusercontent.com/26831442/63533661-cded4000-c53f-11e9-89ca-e66e354e6da7.png)

Link:
 [maya.io structure draft](https://www.gloomaps.com/dwkaEKketK)

**Comment by ericsoncluciano** [comment]
[Website Mockup](https://www.figma.com/file/cG11ALx4klGm2D9RC80ifP/Website?node-id=2%3A2)des

See the home page design

also @johnhigginsavila can i get your email to invite you

**Comment by johnhigginsavila** [comment]
Hi @ericsoncluciano I got the invitation. thank you.

**Comment by johnhigginsavila** [comment]
Hi @ericsoncluciano can you post the assets for the website?
Thank you.

**Comment by Joshiiemaru** [comment]
I will do Documentation Page

**Comment by Mackignacio** [comment]
@Joshiiemaru Yeah sure it will be a big help for me.
